name: Freeverb
options:
  bundleIdPrefix: com.example
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    info:
        path: Info.plist
        properties:
            NSMicrophoneUsageDescription: This app processes input audio.
    sources: []
    postCompileScripts:
      - script: |
          ./../../../scripts/build-for-xcode.sh app_egui
        outputFileLists:
            $TARGET_BUILD_DIR/$EXECUTABLE_PATH
